apiVersion: v1
kind: Service
metadata:
  name: chromadb
  namespace: app
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  selector:
    app: chromadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      serviceAccountName: chroma-s3-sa
      containers:
      - name: chromadb
        image: ghcr.io/chroma-core/chroma:1.3.6.dev14
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: IS_PERSISTENT
          value: "TRUE"
        - name: PERSIST_DIRECTORY
          value: /data
        - name: CHROMA_SERVER_AUTHN_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: chromadb-auth
              key: token
        - name: CHROMA_SERVER_AUTHN_PROVIDER
          value: chromadb.auth.token_authn.TokenAuthenticationServerProvider
        - name: CHROMA_SERVER_HOST
          value: "0.0.0.0"
        - name: CHROMA_SERVER_HTTP_PORT
          value: "8000"
        volumeMounts:
        - name: chroma-data
          mountPath: /data
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: chroma-data
        persistentVolumeClaim:
          claimName: chroma-data-pvc
