apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: app
data:
  CHROMA_URL: http://chromadb:8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sktrinh12/llm-ado-chat-app:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
          env:
          - name: CHROMA_TOKEN
            valueFrom:
              secretKeyRef:
                name: chromadb-auth
                key: token 
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-secret
                key: HF_TOKEN
          - name: CHROMA_URL
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: CHROMA_URL
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: app
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
